spring:
  datasource:
    url: jdbc:mysql://localhost:3307/togetharttest?useSSL=false&autoReconnect=true&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Seoul
    username: togetharttest
    password: 2gethart
    schemas: ['togetharttest'] # 스키마 소문자.

mybatis:
  mapper-locations: classpath:mappers/**/*.xml  # mapper/**/*.xml -> 폴더에 있을때
  configuration:
    map-underscore-to-camel-case: true
---
spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 567588959844-bq3mes74mkhpf1p2ogmvcmj11t3a9ln7.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: http://localhost:8080/login/oauth2/code/google
            scope: profile,email
---
spring:
  profiles:
    include: oauth

---
spring:
  mail:
    protocol: smtp
    host: smtp.gmail.com
    port: 587
    username: songtjdwn@gmail.com
    password: dghzxxgpraglgcav
    default-encoding: utf-8
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true


